export const darkTheme = {
    defaultBackground:'#000',
    defaultFontColor: '#abb1ba',
    cardBordercolor:'#3C4858',
    cardBackground: '#333',
    solidButtonBackground: '#4BD5EE',
    solidButtonBorderColor: 'none',
    solidButtonFontColor: '#FFE300',
    inputBackground: '#FFF',
    inputBorderColor: '#3C4858',
    inputFontColor: '#273444',
    outlineButtonsBackground: '#333',
    outlineButtonsBordercolor: '#3C4858',
    appBarBackground: '#333',
    appBarBorderColor: '#3C4858',
    appBarFontColor: '#4BD5EE',
    primaryHeadingFontColor: '#FFE300',
    radarFontColor: '#FFE300',
    radarBackground: '#000',
    radarGrid: '#333',
  };