export const lightTheme = {
    defaultBackground: '#E8EAED',
    defaultFontColor: '#4E5B6E',
    cardBordercolor:'#E5E9F2',
    cardBackground: '#FFF',
    solidButtonBackground: '#000',
    solidButtonBorderColor: '#E5E9F2',
    solidButtonFontColor: '#FFE300',
    inputBackground: '#EFF2F7',
    inputBorderColor: '#E5E9F2',
    inputFontColor: '#3C4858',
    outlineButtonsBackground: '#EFF2F7',
    outlineButtonsBordercolor: '#E5E9F2',
    appBarBackground: '#000',
    appBarBorderColor: '#333',
    appBarFontColor: '#4BD5EE',
    primaryHeadingFontColor: '#4BD5EE',
    radarFontColor: '#4BD5EE',
    radarBackground: '#000',
    radarGrid: '#3C4858',
  };